import Head from 'next/head'
import {Inter} from 'next/font/google'
import Header from "../../components/header";
import Category from "../../components/category";
import Sort from "../../components/sort";
import Pizza from "../../components/pizza";
import {useEffect} from "react";
import Skeleton from "../../components/skeleton";
import {fetchPizza} from "../../redux/apiSlice";
import ErrorMessage from "../../components/errorMessage";
import {useAppDispatch, useAppSelector} from "../../hooks";

//const inter = Inter({subsets: ['latin']})

export default function Home() {

    const dispatch = useAppDispatch()

    //pizzas data
    const pizzas = useAppSelector(state => state.api.pizzas)

    //sort
    const sortLabel: string[] = ["popularity", "price", "title"]
    const activeSort = useAppSelector(state => state.filter.activeSort)

    //category
    const activeCategory = useAppSelector(state => state.filter.activeCategory)

    //loading
    const loading = useAppSelector(state => state.api.loading)

    //search
    const term = useAppSelector(state => state.filter.term)

    //error message
    const error = useAppSelector(state => state.api.error)


    useEffect(() => {
        dispatch(fetchPizza({sortLabel, activeSort}))
    }, [dispatch, activeSort])


    const filterByCategory = activeCategory === 0 ? pizzas : pizzas.filter(item => item.category === activeCategory)

    const searching = term === "" ? filterByCategory : filterByCategory.filter(item => item.title.toLowerCase().includes(term.toLowerCase()))

    if (error) {
        return <ErrorMessage/>
    }

    return (
        <>
            <Head>
                <title>Pizza Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="wrapper">
                <Header/>
                <div className="content">
                    <div className="container">
                        <div className="content__top">
                            <Category/>
                            <Sort/>
                        </div>
                        <h2 className="content__title">All pizzas</h2>
                        <div className="content__items">

                            {loading ? [...new Array(9)].map((_, i) => <div className="pizza-block" key={i}>
                                <Skeleton uniqueKey={15}/>
                            </div>) : searching.map(item => <Pizza key={item.id} {...item}/>)}
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
