import Head from 'next/head'
import {Inter} from 'next/font/google'
import Header from "../../components/header";
import Category from "../../components/category";
import Sort from "../../components/sort";
import Pizza from "../../components/pizza";
import {useEffect, useState} from "react";
import Skeleton from "../../components/skeleton";

//const inter = Inter({subsets: ['latin']})

export default function Home() {

    //pizzas data
    const [pizzas, setPizzas] = useState([])

    //sort
    const sortLabel = ["popularity", "price", "title"]
    const [activeSort, setActiveSort] = useState(0)

    //category
    const [activeCategory, setActiveCategory] = useState(0)

    //loading
    const [loading, setLoading] = useState(true)


    useEffect(() => {
        setLoading(true)
        getPizzas()
        setLoading(false)
    }, [activeSort])

    const getPizzas = async () => {
        const res = await fetch(`https://64560f792e41ccf16912d161.mockapi.io/items?sortBy=${sortLabel[activeSort]}`)
        const data = res.json()
            .then(data => setPizzas(data))
    }

    const filterByCategory = activeCategory === 0 ? pizzas : pizzas.filter(item => item.category === activeCategory)

    return (
        <>
            <Head>
                <title>Pizza Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="wrapper">
                <Header/>
                <div className="content">
                    <div className="container">
                        <div className="content__top">
                            <Category activeCategory={activeCategory} setActiveCategory={setActiveCategory}/>
                            <Sort activeSort={activeSort} setActiveSort={setActiveSort}/>
                        </div>
                        <h2 className="content__title">All pizzas</h2>
                        <div className="content__items">
                            {loading ? [...new Array(9)].map((item, i) => <div className="pizza-block" key={i}>
                                <Skeleton uniqueKey={15}/>
                            </div>) : filterByCategory.map(item => <Pizza key={item.id} {...item}/>)}
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
