import Head from 'next/head'
import {Inter} from 'next/font/google'
import Header from "../../components/header";
import Category from "../../components/category";
import Sort from "../../components/sort";
import Pizza from "../../components/pizza";
import {useEffect, useState} from "react";

//const inter = Inter({subsets: ['latin']})

export default function Home() {

    //pizzas data
    const [pizzas, setPizzas] = useState([])

    useEffect(() => {
        getPizzas()
    }, [])

    const getPizzas = async () => {
        const res = await fetch(`https://64560f792e41ccf16912d161.mockapi.io/items`)
        const data = res.json()
            .then(data => setPizzas(data))
    }

    return (
        <>
            <Head>
                <title>Pizza Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="wrapper">
                <Header/>
                <div className="content">
                    <div className="container">
                        <div className="content__top">
                            <Category/>
                            <Sort/>
                        </div>
                        <h2 className="content__title">All pizzas</h2>
                        <div className="content__items">
                            {pizzas.map(item => <Pizza key={item.id} {...item}/>)}
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
